version: '3'

services:
  web:
    build: './web'
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        window: 3s
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'
    command: >
      gunicorn -b 0.0.0.0:5000
      --access-logfile -
      --reload
      --chdir ./web
      'app:create_app()'
    links:
      - db

  db:
    image: mysql:8
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - 'dbdata:/var/lib/mysql'
    env_file:
      - '.env'

  redis:
    image: redis:5-alpine
    restart: always

volumes:
  dbdata:
